<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
	>

<channel>
	<title>Madison Hash House Harriers</title>
	<atom:link href="http://madisonh3.com/feed/" rel="self" type="application/rss+xml" />
	<link>http://madisonh3.com</link>
	<description>Drinking Club with a Running Problem</description>
	<lastBuildDate>Sun, 26 Mar 2017 20:18:39 +0000</lastBuildDate>
	<language>en-US</language>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.7.3</generator>
</channel>
</rss>

<!-- Dynamic page generated in 0.582 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-04-20 03:24:41 -->
